-- require is called on folders in the lua directory
require("thebasics")
-- require("temp_old")
-- require("plugins")
require("after.plugins.telescope")
require("after.plugins.colors")
require("after.plugins.lsp_zero")
require("after.plugins.gitsigns")
require("after.plugins.harpoon")
require("after.plugins.undotree")
